# Generated by Django 5.1.6 on 2025-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('amenities', models.TextField(help_text='Разделяйте запятыми')),
                ('opening_hours', models.CharField(max_length=100)),
                ('promo_text', models.CharField(blank=True, max_length=200)),
                ('promo_price', models.CharField(blank=True, max_length=50)),
                ('distance', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='gyms/')),
            ],
        ),
    ]
