# Generated by Django 5.1.6 on 2025-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='promo_price',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='promo_text',
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours_saturday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours_sunday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours_weekdays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gym',
            name='amenities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gyms/'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
