# Generated by Django 5.1.6 on 2025-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_maps', '0002_remove_gym_distance_remove_gym_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
