# Generated by Django 5.1.6 on 2025-04-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_maps', '0003_gym_city_gym_email_gym_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gyms/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='google_maps.gym')),
            ],
        ),
    ]
