# Generated by Django 5.1.6 on 2025-05-03 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_maps', '0004_gymimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
