# Generated by Django 5.1.6 on 2025-04-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('height', models.PositiveIntegerField(verbose_name='Height (cm)')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary lifestyle (little or no physical activity)'), ('light', 'Light activity (1-3 workouts per week)'), ('moderate', 'Moderate activity (3-5 workouts per week)'), ('active', 'High activity (6-7 workouts per week)'), ('very_active', 'Very high activity (heavy physical work or training 2 times a day)')], max_length=20, verbose_name='Activity level')),
                ('goal', models.CharField(choices=[('lose', 'Weight loss'), ('maintain', 'Maintenance'), ('gain', 'Weight gain')], max_length=10, verbose_name='Goal')),
                ('bmr', models.FloatField(blank=True, null=True, verbose_name='Basal Metabolic Rate (BMR)')),
                ('daily_calories', models.FloatField(blank=True, null=True, verbose_name='Daily calorie intake')),
                ('target_calories', models.FloatField(blank=True, null=True, verbose_name='Target calorie intake')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calorie profile',
                'verbose_name_plural': 'Calorie Profiles',
            },
        ),
    ]
