# Generated by Django 5.1.6 on 2025-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieprofile',
            name='goal',
            field=models.CharField(choices=[('lose_0.5', 'Lose 0.5 kg/week'), ('lose_1', 'Lose 1 kg/week'), ('lose_2', 'Lose 2 kg/week'), ('maintain', 'Maintain weight'), ('gain_0.5', 'Gain 0.5 kg/week'), ('gain_1', 'Gain 1 kg/week'), ('gain_2', 'Gain 2 kg/week')], max_length=10, verbose_name='Goal'),
        ),
    ]
